name: Finnpanel Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 08:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Display FPGH.py contents
      run: cat FPGH.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: Run scraper
      env:
        GT_TOKEN: ${{ secrets.GT_TOKEN }}
      run: |
        echo "GT_TOKEN is set: ${{ secrets.GT_TOKEN != '' }}"
        python -u FPGH.py
