name: Update Finnpanel Data

on:
  schedule:
    - cron: '0 1 * * *'  # Suoritetaan joka p채iv채 klo 01:00 UTC
  workflow_dispatch:  # Mahdollistaa manuaalisen k채ynnistyksen

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas openpyxl PyGithub numpy

    - name: Run Finnpanel scraper (creates/updates files via GitHub API)
      run: python FPGH.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update README
      run: |
        # Hae viimeisin, koska edellinen steppi teki commitit API:n kautta
        git fetch origin
        git pull --rebase

        echo "# Finnpanel Data" > README.md
        echo "" >> README.md
        echo "Viimeisin p채ivitys: $(date -u)" >> README.md
        echo "" >> README.md
        echo "## Saatavilla olevat tiedostot" >> README.md
        echo "- 14D_Finnpanel_data_$(date -u +%Y-%m-%d).xlsx" >> README.md
        echo "- 90D_Finnpanel_data_$(date -u +%Y-%m-%d).xlsx" >> README.md

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README" || echo "No changes to commit"
        git push origin || echo "No changes to push"
