name: Update Finnpanel Data

on:
  schedule:
    - cron: '0 1 * * *'  # Suoritetaan joka p채iv채 klo 01:00 UTC
  workflow_dispatch:  # Mahdollistaa manuaalisen k채ynnistyksen

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas openpyxl

    - name: Run Finnpanel scraper for 14 days
      run: python finnpanel_scraper.py --period 14
      env:
        GT_TOKEN: ${{ secrets.GT_TOKEN }}

    - name: Run Finnpanel scraper for 90 days
      run: python finnpanel_scraper.py --period 90
      env:
        GT_TOKEN: ${{ secrets.GT_TOKEN }}

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Finnpanel data (14 and 90 days)" && git push)

    - name: Update README
      run: |
        echo "# Finnpanel Data" > README.md
        echo "" >> README.md
        echo "Viimeisin p채ivitys: $(date)" >> README.md
        echo "" >> README.md
        echo "## Saatavilla olevat tiedostot" >> README.md
        echo "- 14D_Finnpanel_data_$(date +%Y-%m-%d).csv" >> README.md
        echo "- 90D_Finnpanel_data_$(date +%Y-%m-%d).csv" >> README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README" || echo "No changes to commit"
        git push origin || echo "No changes to push"
